import { loadThree } from '../lib/studio.js';
import { createRealScene } from '../lib/real-scene.js';
const photos=[
 {file:'IMG_2206.jpg',title:'Work area & lounge',note:'Ceiling lights, white desks, rolling whiteboard and black lounge seating.'},
 {file:'IMG_2207.jpg',title:'Kitchenette & circulation',note:'White cabinetry, dark counter, sink, coffee equipment and glass-framed openings.'},
 {file:'IMG_2208.jpg',title:'Windows & workstations',note:'Tall windows with vertical blinds, multi-monitor desks and gray carpet.'},
 {file:'IMG_2209.jpg',title:'Desk and glass details',note:'White desk frames, task chairs, black-framed glass and striped carpet.'},
 {file:'IMG_2210.jpg',title:'Glass enclosure & lounge',note:'Full-height glass, white cabinetry, mobile whiteboards and dark seating.'}
];
export default async function render(ctx){
 const root=ctx.content;
 root.innerHTML=`<div class="studio real-studio"><header class="masthead"><div class="identity"><span class="brand-mark">◈</span><div><span class="eyebrow">SUITE 530 / PHOTO-GUIDED INTERIOR</span><h1>The office<span class="title-dot">.</span></h1></div></div><nav aria-label="Model views"><a href="home">3D model</a><a href="plan">Floor plan</a><a href="furnishing">Furnishing</a><a href="realistic" aria-current="page">Realistic view</a></nav><div class="concept"><span></span>Rendered concept</div></header>
 <div class="real-intro"><div><span class="eyebrow">04 / REALISTIC VIEW</span><h2>Your space, in a different light.</h2><p>Walk through the photo-guided office at eye level. A proposed ten-seat workspace.</p></div><div class="real-provenance"><strong>5 reference photographs</strong><span>Based on your uploads + Exhibit A</span></div></div>
 <div class="real-disclaimer"><strong>Photo-guided reconstruction, not a measured scan.</strong> Materials follow the photos; glazing locations, furniture placement, scale and lighting are inferred. The ten-desk arrangement is the proposed layout, not a claim about the current office.</div>
 <main class="real-layout"><section class="real-scene-panel"><div class="real-stage"><div class="real-stage-top"><span id="real-view-title">Workspace · eye level</span><button type="button" class="real-interact" aria-pressed="false">Interact</button></div><div class="real-canvas"><div class="real-load" role="status">Building the photo-guided interior…</div></div><div class="real-walk-pad" aria-label="Walking controls" hidden><button type="button" data-move="turnLeft" aria-label="Turn left" title="Turn left (Q)">↶</button><button type="button" data-move="forward" aria-label="Walk forward" title="Walk forward (W)">↑</button><button type="button" data-move="turnRight" aria-label="Turn right" title="Turn right (E)">↷</button><button type="button" data-move="left" aria-label="Step left" title="Step left (A)">←</button><button type="button" data-move="back" aria-label="Walk backward" title="Walk backward (S)">↓</button><button type="button" data-move="right" aria-label="Step right" title="Step right (D)">→</button><span>Hold to move</span></div><div class="real-camera-tools" hidden><button type="button" id="real-walk" aria-pressed="false">Walk</button><button type="button" id="real-minus" aria-label="Zoom out">−</button><button type="button" id="real-plus" aria-label="Zoom in">+</button><button type="button" id="real-reset">Reset view</button></div><div class="real-gesture">W/A/S/D to walk · Drag to look · Esc to pause</div></div>
 <div class="real-walk-info"><span id="real-walk-status" role="status" aria-live="polite">Click Walk, then use W/A/S/D or hold the arrows.</span><details><summary>Walking help</summary><p>Click Walk to focus the scene. W/A/S/D or arrow keys move; Q/E turn. Drag to look around. Hold the on-screen arrows on touchscreens. Escape pauses; Reset view returns to the selected camera position. Choosing Whole suite pauses walking; Walk returns you indoors.</p><p>Eye level is fixed at 1.6 m. Collision checks use the modeled walls, glass and visible furniture; they are approximate, not a real-world accessibility or clearance assessment. Camera presets can jump between rooms.</p></details></div>
 <div class="real-views" aria-label="Camera positions"><button type="button" data-view="workspace" aria-pressed="true" disabled><span>01</span>Workspace</button><button type="button" data-view="windows" aria-pressed="false" disabled><span>02</span>Window side</button><button type="button" data-view="kitchenette" aria-pressed="false" disabled><span>03</span>Kitchenette</button><button type="button" data-view="lounge" aria-pressed="false" disabled><span>04</span>Lounge</button><button type="button" data-view="overview" aria-pressed="false" disabled><span>05</span>Whole suite</button></div>
 <div class="real-scene-controls"><label><input type="checkbox" id="real-lights" checked disabled>Ceiling lights</label><label><input type="checkbox" id="real-blinds" checked disabled>Vertical blinds</label><label><input type="checkbox" id="real-furniture" checked disabled>Furniture</label><span>Assumed width 10 m · ceiling 3 m</span></div></section>
 <aside class="real-reference"><div class="reference-heading"><span class="eyebrow">REAL OFFICE / REFERENCE</span><h3>From the photographs</h3><p>Compare the rendered interpretation with the actual office.</p></div><button type="button" class="real-photo-main" aria-label="Enlarge reference photograph"><img id="real-photo" src="assets/photos/IMG_2206.jpg" alt="Office workstations, rolling whiteboard, ceiling lights and lounge seating"><span>View original ↗</span></button><div class="real-photo-caption"><strong id="real-photo-title"></strong><p id="real-photo-note"></p></div><div class="real-thumbnails">${photos.map((p,i)=>`<button type="button" data-photo="${i}" aria-label="View ${p.title}" aria-pressed="${i===0}"><img src="assets/photos/${p.file}" alt="${p.title}" loading="lazy"></button>`).join('')}</div>
 <details class="real-evidence"><summary>What matches—and what is inferred</summary><h4>Visible in your photos</h4><p>Gray striped carpet, white walls and cabinetry, black-framed glass, vertical blinds, suspended ceiling panels, recessed lighting, light desks, task chairs and dark lounge seating.</p><h4>Still a design interpretation</h4><p>Window and glass-panel locations on the floor plan, furniture dimensions and placement, ceiling height and tile sizes, lighting intensity, and unseen surfaces. This is a real-time 3D rendering, not photogrammetry or an exact photographic replica.</p><p>The fixed 10 m overall width and 3 m ceiling are assumptions inherited from the model. Workstations use the proposed 1.4 × 0.7 m desks. Shared furniture placement is illustrative. No accessibility, electrical or egress compliance is established.</p></details></aside></main>
 <footer class="studio-footer"><span><span class="status-dot"></span>Sources: IMG_2206–IMG_2210 + Exhibit A suite 530.pdf</span><span>Photo-inspired materials · Inferred placement · Not for construction</span></footer>
 <dialog class="real-photo-dialog"><div><strong id="dialog-photo-title">Office reference</strong><button type="button" id="real-photo-close">Close ×</button></div><img id="dialog-photo" alt="Office reference photograph"></dialog></div>`;
 const q=s=>root.querySelector(s),on=(el,event,fn)=>el.addEventListener(event,fn,{signal:ctx.signal});
 let photoIndex=0,viewer;
 const showPhoto=i=>{photoIndex=i;const p=photos[i];q('#real-photo').src='assets/photos/'+p.file;q('#real-photo').alt=p.note;q('#real-photo-title').textContent=p.title;q('#real-photo-note').textContent=p.note;root.querySelectorAll('[data-photo]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.photo)===i)));};
 showPhoto(0);root.querySelectorAll('[data-photo]').forEach(b=>on(b,'click',()=>showPhoto(Number(b.dataset.photo))));
 const dialog=q('.real-photo-dialog');on(q('.real-photo-main'),'click',()=>{q('#dialog-photo').src='assets/photos/'+photos[photoIndex].file;q('#dialog-photo-title').textContent=photos[photoIndex].file;viewer?.stopWalk();dialog.showModal();});on(q('#real-photo-close'),'click',()=>dialog.close());on(dialog,'click',e=>{if(e.target===dialog)dialog.close();});
 const touch=matchMedia('(pointer:coarse)');
 function setInteraction(active){q('.real-stage').classList.toggle('interacting',active);q('.real-interact').textContent=active?'Done · scroll':'Interact';q('.real-interact').setAttribute('aria-pressed',String(active));viewer?.setWalkEnabled(!touch.matches||active);q('.real-gesture').textContent=touch.matches?(active?'Hold arrows to walk · Drag to look':'Tap Walk or Interact to explore'):'W/A/S/D to walk · Drag to look · Esc to pause';}
 function updateTouch(){q('.real-stage').classList.toggle('is-touch',touch.matches);setInteraction(false);}updateTouch();on(touch,'change',updateTouch);
 on(q('.real-interact'),'click',()=>setInteraction(!q('.real-stage').classList.contains('interacting')));
 try{
  const [rows]=await Promise.all([ctx.db.rows('SELECT id, kind, x1, y1, x2, y2, label FROM geometry ORDER BY id LIMIT 200'),loadThree()]);if(ctx.signal.aborted)return;
  if(!rows.length)throw new Error('The schematic geometry is unavailable.');
  q('.real-load').remove();viewer=createRealScene(q('.real-canvas'),rows);
  q('.real-camera-tools').hidden=false;q('.real-walk-pad').hidden=false;root.querySelectorAll('.real-views button,.real-scene-controls input').forEach(e=>e.disabled=false);
  viewer.setWalkEnabled(!touch.matches);
  on(q('.real-canvas canvas'),'walkstatus',e=>{const {active,blocked,view,message}=e.detail;q('#real-walk').textContent=active?'Pause':'Walk';q('#real-walk').setAttribute('aria-pressed',String(active));q('.real-stage').classList.toggle('is-walking',active);q('#real-walk-status').textContent=message;q('#real-walk-status').classList.toggle('walk-blocked',blocked);if(active){q('#real-view-title').textContent='Walkthrough · eye level 1.6 m';root.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));}});
  on(q('#real-walk'),'click',()=>{if(viewer.navigationState().active)viewer.stopWalk();else{if(touch.matches)setInteraction(true);viewer.startWalk();}});
  root.querySelectorAll('[data-move]').forEach(button=>{
   on(button,'pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);if(touch.matches)setInteraction(true);viewer.pressMove('pointer-'+e.pointerId,button.dataset.move);button.classList.add('is-held');});
   for(const event of ['pointerup','pointercancel','lostpointercapture'])on(button,event,e=>{viewer.releaseMove('pointer-'+e.pointerId);button.classList.remove('is-held');});
   on(button,'keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();if(touch.matches)setInteraction(true);viewer.pressMove('key-'+button.dataset.move,button.dataset.move);button.classList.add('is-held');}});
   on(button,'keyup',e=>{if(e.key===' '||e.key==='Enter'){viewer.releaseMove('key-'+button.dataset.move);button.classList.remove('is-held');}});
   on(button,'blur',()=>{viewer.releaseMove('key-'+button.dataset.move);button.classList.remove('is-held');});
  });
  root.querySelectorAll('[data-view]').forEach(b=>on(b,'click',()=>{viewer.setView(b.dataset.view);root.querySelectorAll('[data-view]').forEach(v=>v.setAttribute('aria-pressed',String(v===b)));q('#real-view-title').textContent=b.textContent.replace(/^\d+\s*/,'').trim()+(b.dataset.view==='overview'?' · roof removed':' · eye level');}));
  for(const key of ['lights','blinds','furniture'])on(q('#real-'+key),'change',e=>viewer.setOption(key,e.target.checked));
  on(q('#real-minus'),'click',()=>viewer.zoom(1/1.15));on(q('#real-plus'),'click',()=>viewer.zoom(1.15));on(q('#real-reset'),'click',()=>viewer.reset());
 }catch(error){if(ctx.signal.aborted)return;const el=document.createElement('p');el.className='real-load';el.setAttribute('role','alert');el.textContent=error.message;q('.real-canvas').appendChild(el);ctx.reportError(error);}
 return ()=>{viewer?.dispose();dialog.close();};
}
